# Generated by Django 3.1.4 on 2020-12-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_passwordresetcodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwordresetcodes',
        ),
    ]
