# Generated by Django 3.1.4 on 2020-12-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201231_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='text',
        ),
    ]
