# Generated by Django 3.1.4 on 2020-12-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_todos_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
